### ISSUE TITLE
implement largest-series-product

### ISSUE THREAD

**Issue by lilislilit** [exercism/typescript#70] opened 2017-09-28 13:38 UTC
As per #37, port exercise from ecmascript track

**Comment by deyshin** [comment] 2017-10-10 15:58
I'll work on this. 
Let's see how my evening goes.

**Comment by masters3d** [comment] 2017-10-14 20:17
https://github.com/exercism/typescript/pull/94

**Comment by deyshin** [comment] 2017-10-17 00:42
Setting up WSL to properly `make test` took a lot longer than I thought. I'm getting to it tomorrow finally. My apologies for the delay on such a simple task!

**Comment by deyshin** [comment] 2017-10-18 00:49
Got it. I did not need to touch `make test` indeed. Thank you for the input! 
I submitted the [#108](https://github.com/exercism/typescript/pull/108). Please let me know if the PR needs any changes!

**Comment by deyshin** [comment] 2017-10-20 12:03
I believe the issue is closed by the #108. Anything more to add?

**Closed** 2017-10-20 19:26 UTC
Labels: hacktoberfest
